   CREATE TABLE CUSTOMERS
   (
   CUSTOMERID NUMBER(10) NOT NULL,
   CUSTOMER_NAME VARCHAR(34),
   EMAIL VARCHAR(34),
   PHONE NUMBER(10),
   LOCATION VARCHAR(32),
   ENTRY_DATE DATE,
   CONSTRAINT PK_CUSTOMERID PRIMARY KEY (CUSTOMERID)
   )
   

   CREATE TABLE PRODUCT
   (
   PRODUCTID  NUMBER(10) NOT NULL CONSTRAINT PID_PK PRIMARY KEY,
   PRODUCTNAME VARCHAR(32) NOT NULL,
   CATEGORY VARCHAR(32),
   PRICE NUMBER(10,2),
   STOCK NUMBER(10)
   )
   
   CREATE TABLE SALESORDER
   (
   
   ORDERID NUMBER(10) NOT NULL ,
   CUSTOMERID NUMBER(10) NOT NULL, 
   ORDERDATE DATE,
   TOTALAMOUNT NUMBER (10,10),
   CONSTRAINT PK_ORDERID PRIMARY KEY (ORDERID),
   CONSTRAINT FK_CUSTOMERID foreign key (CUSTOMERID) references CUSTOMERS (CUSTOMERID)   
   )
   
   CREATE TABLE ORDERDETAILS
   (
   ORDER_DETAILS_ID NUMBER(10) NOT NULL,
   ORDERID NUMBER (10) NOT NULL,
   PRODUCTID  NUMBER(10) NOT NULL,
   Quantity NUMBER (10) ,
   SUBTOTAL NUMBER(10),
   CONSTRAINT PK_ORDER_DETAILS_ID  PRIMARY KEY (ORDER_DETAILS_ID),
   CONSTRAINT FK_ORDERID  foreign key (ORDERID) references SALESORDER (ORDERID),
   CONSTRAINT FK_PRODUCTID foreign key (PRODUCTID) references PRODUCT (PRODUCTID)
   
   )
   
   
   
   CREATE TABLE PAYMENTS
   (
   PAYMENT_ID NUMBER(10) NOT NULL,
    ORDERID NUMBER (10) NOT NULL,
    PAYMENTMETHOD VARCHAR(32),
    AMOUNT NUMBER(10),
    PAYMENTDATE DATE,
    CONSTRAINT PK_PAYMENT_ID  PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT FK_ORDER_ID  foreign key (ORDERID) references SALESORDER (ORDERID)
   )
    
    
    CREATE TABLE  CUSTOMERS_1
	(
    CUSTOMERID  NUMBER  NOT NULL  ,
	NAME 					VARCHAR2(34),
	EMAIL					VARCHAR(34),
	PHONE					NUMBER,
	LOCATION 				VARCHAR2(32),
	PRIMARY KEY (CUSTOMERID)
	)
   
--   SELECT *
--  FROM user_cons_columns
-- WHERE table_name = 'CUSTOMERS';



--drop table customers;
--drop table customers_1;
--drop table orderdetails;
--drop table payments;

--drop table product;
--drop table salesorder;
